@startuml タイトル
start
repeat :商品番号入力;
    :番号をカウント;
    backward :もう一度番号を入力;
repeat while (支払に進む場合はcを押す)
    :商品の情報とそれぞれのカウント
    された商品番号を表示;
    :合計金額を表示;
repeat 
    :ユーザーに金額を入力してもらう;
    repeat while (入金額) is (足りない) not (足りる)
    if (会計) then (おつりがあり)
    :おつり金額を表示し、
    「ありがとうございました」
    と出力;
    end
    else (おつりなし)
    :「ありがとうございました」
    と出力;
    end

@enduml