@startwbs 券売機WBS
title 券売機WBS

+ 券売機
**[#Red]  Please Enter
***[#Yellow] 1,購入可能な商品一覧を表示し、商品番号の入力を受け付けてください。
***[#Yellow] 2,cが入力されるまで繰り返し入力をうけつけてください。
***[#Yellow] 3,商品番号とc以外の値が入力されたら、下記のメッセージを表示して、再度入力を受け付けてください。
***[#Yellow] 4,商品番号またはcを指定してください。
***[#Yellow] 5,cが入力されたら、購入する商品の一覧と金額の合計を表示してください。
***[#Yellow] 6,さらに、下記のように表示し、金額の入力を受け付けてください。
***[#Yellow] 7,ユーザーが入力した金額が、購入対象の金額より小さい場合は下記のエラーを表示して、タイトル画面に戻ってください。
***[#Yellow] 8,ユーザーが入力した金額が正の数でない場合は、エラーを表示してタイトル画面に戻ってください。
***[#Yellow] 9,おつりを計算して返却します。下記のように表示してください。
@endwbs