@startwbs 支払い処理WBS
title 支払い処理WBS

+ 支払い処理
**[#Red]  支払い処理
***[#Yellow] 購入する商品番号を受付(1~4)
***[#Yellow] 購入する商品の数量をカウント
***[#Yellow] 合計金額を表示
***[#Yellow] 「現金を投入してください」と表示
***[#Yellow] 合計金額以上のお金を受付
***[#Yellow] 「ご購入ありがとうございました。」と表示
***[#Yellow] おつりを計算
***[#Yellow] おつりを表示
@endwbs
